steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'asia.gcr.io/${PROJECT_ID}/spring/${_APP}:${SHORT_SHA}', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'asia.gcr.io/${PROJECT_ID}/spring/${_APP}:${SHORT_SHA}']

substitutions:
  _APP: "demo"
